software-deployment-method:
  - conda
executor: lsf
default-resources:
  mem: 8
  # Specific for Logsdon Lab
  lsf_queue: epistasis_long
  lsf_project: default
printshellcmds: True
rerun-incomplete: True
show-failed-logs: True
rerun-triggers: mtime
