samples:
  mPanTro3:
    threads: 40
    mem: 250GB
    data:
      ont:
        path: /project/logsdon_shared/data/PrimateT2T/ont/mPanTro3
        include: ["*.fq.gz"]
        exclude: ["*old-guppy-runs/*", "*.bam*", "*fast5/*"]
      hifi:
        path: /project/logsdon_shared/data/PrimateT2T/hifi_data/mPanTro3
        include: ["*.hifi_reads.fq.gz"]
        exclude: ["*previous-versions/*", "*.bam*", "*ccs*"]
      hic:
        path: /project/logsdon_shared/data/PrimateT2T/dovetail_hic/mPanTro3
        include: ["*.fastq.gz"]
