samples:
  mPanTro3:
    threads: 40
    assembler: hifiasm
    mem: 250GB
    data:
      ont:
        path: /project/logsdon_shared/data/PrimateT2T/ont/mPanTro3
        include: ["*.fq.gz"]
      hic_mat:
        path: /project/logsdon_shared/data/PrimateT2T/dovetail_hic/mPanTro3
        include: ["*R1*fastq.gz"]
      hic_pat:
        path: /project/logsdon_shared/data/PrimateT2T/dovetail_hic/mPanTro3
        include: ["*R2*fastq.gz"]
